sonar.projectKey=dita-devops-portfolio
sonar.projectName=Dita DevOps Portfolio
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/*.test.*,**/node_modules/**,**/.next/**,**/public/**,**/scripts/**
sonar.javascript.environments=browser,node